# Generated by Django 3.1.7 on 2021-03-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattegory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(default='', max_length=200)),
                ('is_receita', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cattegory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fino.cattegory'),
        ),
    ]
