# Generated by Django 3.1.7 on 2021-03-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fino', '0006_auto_20210328_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='time',
            new_name='date',
        ),
    ]
